apps/controllers/carts/controllers.py
from flask import Blueprint, render_template

from apps.common.auth import signin_required
from apps.controllers.carts import get_carts
from apps.controllers.orders import get_orders
from apps.database.models import Category

app = Blueprint('carts', __name__, url_prefix='/carts')


@app.route('', methods=['GET'])
@signin_required
def index():
    categories = Category.query.all()
    return render_template('carts/index.html', carts=get_carts(), categories=categories, orders=get_orders())

apps/controllers/index/controllers.py
from flask import Blueprint, send_from_directory, render_template

from apps.controllers.carts import get_carts
from apps.controllers.orders import get_orders
from apps.database.models import Category, Product
from config import Config

app = Blueprint('index', __name__, url_prefix='/')


@app.route('/', methods=['GET'])
def index():
    categories = Category.query.all()
    products = Product.query.order_by(Product.id.desc()).limit(12).all()
    return render_template('main/index.html', categories=categories, products=products, orders=get_orders(), carts=get_carts())


@app.route('favicon.ico')
def favicon():
    return send_from_directory(Config.STATIC_DIR, 'favicon.ico', mimetype='image/vnd.microsoft.icon')

apps/controllers/orders/controllers.py
from flask import Blueprint, render_template

from apps.common.auth import signin_required
from apps.controllers.carts import get_carts
from apps.controllers.orders import get_orders
from apps.database.models import Category

app = Blueprint('orders', __name__, url_prefix='/orders')


@app.route('', methods=['GET'])
@signin_required
def index():
    categories = Category.query.all()
    return render_template('orders/index.html', carts=get_carts(), categories=categories, orders=get_orders())

apps/controllers/users/controllers.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, logout_user, current_user

from apps.common.auth import SHA256, already_signin, signin_required
from apps.controllers.carts import get_carts
from apps.controllers.users.forms import SignInForm, SignUpForm, ProfileForm
from apps.database.models import User, Category, Order, Delivery
from apps.database.session import db

app = Blueprint('users', __name__, url_prefix='/users')


@app.route('/profile', methods=['GET', 'POST'])
@signin_required
def profile():
    form = ProfileForm()

    delivery = Delivery.query.filter(Delivery.user_id == current_user.id).first()
    if form.validate_on_submit():
        if delivery:
            delivery.username = form.username.data
            delivery.phone = form.phone.data
            delivery.address = form.address.data
            delivery.detail_address = form.detail_address.data
        else:
            delivery = Delivery(username=form.username.data, address=form.address.data,
                                detail_address=form.detail_address.data, phone=form.phone.data,
                                user_id=current_user.id)
            db.session.add(delivery)
        db.session.commit()
        return redirect(url_for('index.index'))

    if delivery:
        form.username.data = delivery.username
        form.phone.data = delivery.phone
        form.address.data = delivery.address
        form.detail_address.data = delivery.detail_address

    categories = Category.query.all()
    orders = Order.query.filter(Order.user_id == current_user.id).all()
    return render_template('users/profile.html', categories=categories, orders=orders, carts=get_carts(), form=form)


@app.route('/signin', methods=['GET', 'POST'])
@already_signin
def signin():
    form = SignInForm()

    if form.validate_on_submit():
        user = User.query.filter(User.email == form.email.data).first()
        if not user:
            form.email.errors.append('가입하지 않은 이메일 입니다.')
            return render_template('users/signin.html', form=form)
        if user.password != SHA256.encrypt(form.password.data):
            form.password.errors.append('비밀번호가 일치하지 않습니다.')
            return render_template('users/signin.html', form=form)

        login_user(user)
        return redirect(url_for('index.index'))
    return render_template('users/signin.html', form=form)


@app.route('/signup', methods=['GET', 'POST'])
@already_signin
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        email_user = User.query.filter(User.email == form.email.data).first()
        nickname_user = User.query.filter(User.nickname == form.nickname.data).first()
        if email_user:
            if email_user.email == form.email.data:
                form.email.errors.append('이미 가입된 이메일입니다.')
        if nickname_user:
            if nickname_user.nickname == form.nickname.data:
                form.nickname.errors.append('이미 가입된 닉네임입니다.')

        if form.email.errors or form.nickname.errors:
            return render_template('users/signup.html', form=form)

        user = User(email=form.email.data, nickname=form.nickname.data, password=SHA256.encrypt(form.password.data), point=1000000)
        db.session.add(user)
        db.session.commit()

        login_user(user)
        return redirect(url_for('index.index'))
    return render_template('users/signup.html', form=form)


@app.route('signout', methods=['GET'])
def signout():
    logout_user()
    return redirect(url_for('users.signin'))

templates/layout/base.html
<!doctype html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf-8"/>
  <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap/bootstrap.min.js"></script>
  {% block head %}
  {% endblock %}
</head>
<body>
  <script>
    function getProduct() {
      let page = $("#more").data('page');

      $.ajax({
        url: `{{ url_for('apis_products.products') }}?page=${page}&category_id={% if category %}{{ category.id }}{% endif %}`,
        type: "GET",
        success: function(data) {
          for(let product of data.data) {
            $("#products").append(`
              <div class="col-lg-2 p-0">
                <div class="card">
                  <img src="${product.image_url}" class="card-img-top" alt="">
                  <div class="card-body">
                    <a href="/products/${product.id}">
                      <h5 class="card-title">${product.name}</h5>
                    </a>
                    <p class="card-text"></p>
                  </div>
                </div>
              </div>
            `)
          }
        },
        error(xhr) {
          alert(`${xhr.status} / ${xhr.responseJSON['message']}`);
        }
      });

      page += 1
      $("#more").data('page', page)
    }
    function comma(x) {
      return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    }
  </script>
  {% block body %}
  {% endblock %}
  {% block script %}
  {% endblock %}
</body>

templates/layout/header.html
<div class="container">
  <ul class="nav justify-content-end">
    {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a href="{{ url_for('users.signout') }}">logout</a>
      </li>
    {% else %}
      <li class="nav-item float-right">
        <a href="{{ url_for('users.signin') }}">login</a>
      </li>
    {% endif %}
  </ul>
</div>
<hr class="m-0">
<div class="container">
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link active text-dark" href="{{ url_for('index.index') }}">
        <h2>Flask Shop</h2>
      </a>
    </li>
  </ul>
  <nav class="navbar navbar-light bg-white justify-content-center">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link active" href="{{ url_for('index.index') }}">All</a>
      </li>
      {% for category in categories %}
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('category.get_category', category_id=category.id) }}">{{ category.name.upper() }}</a>
        </li>
      {% endfor %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('orders.index') }}">
          <i class="fa fa-clone" aria-hidden="true">
            <span class="badge badge-dark">{{ orders|length }}</span>
          </i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('carts.index') }}">
          <i class="fa fa-shopping-cart" aria-hidden="true">
            <span class="badge badge-dark">{{ carts|length }}</span>
          </i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.profile') }}">
          <i class="fa fa-user" aria-hidden="true"></i>
        </a>
      </li>
    </ul>
  </nav>
</div>
<hr class="m-0">